Changes for version 0.17.22
SaveCvcParamters: ignore hidden cells.
calibre_cvc: ignore tvf header
calibre_cvc: abort on calibre failure
cvc: no mos diode errors on conditional mos diodes
cvc: print warning if not able to calculate explicit resistance
cvc: no missing mos bias errors if min and max voltage the same
cvc: added flag to ignore analog gate errors
cvc: added analog power type (removed unused reference type)
cvc: SCRC checks for known voltage level
cvc: enable dump unknown logical nets after first min/max
cvc: unknown logical nets must separate min max power
cvc: dump min and max nets with unknown logical nets
cvc: added print for virtual net
cvc: fixed debug and default cvcrc

diff --git a/scripts/calibre_cvc b/scripts/calibre_cvc
--- a/scripts/calibre_cvc
+++ b/scripts/calibre_cvc
@@ -112,6 +112,7 @@ else
 fi
 
 sed -e 's/[   ][      ]*/ /g' \
+	-e 's/^#!/\/\/&/I' \
 	-e 's/^ *LAYOUT PRIMARY/\/\/&/I' \
 	-e 's/^ *LAYOUT PATH/\/\/&/I' \
 	-e 's/^ *SOURCE PRIMARY/\/\/&/I' \
@@ -139,7 +140,12 @@ if [[ $? -eq 1 ]]; then
 else
 	echo "Performing SVS..."
 	calibre -hier -automatch -lvs -64 $rulefile > $log
+	calibreStatus=$?
 	tail -15 $log
+	if [[ $calibreStatus -ne 0 ]]; then
+		echo "ERROR: Calibre status $calibreStatus"
+		exit 1
+	fi
 fi
 
 echo "Removing leading double characters and changing commented parameters ..."
