Changes for version 0.12.3
Bug fixes

Includes updates to
calibre_cvc (rule file parameter)
cvcMakefile (tab fixes)
expand_cell.ps (version check, syntax fix)

diff --git a/scripts/calibre_cvc b/scripts/calibre_cvc
--- a/scripts/calibre_cvc
+++ b/scripts/calibre_cvc
@@ -2,7 +2,7 @@
 
 #   calibre_cvc: runs calibre svs to create a standardized netlist
 
-#   Copyright 2106, 2017 D. Mitch Bailey
+#   Copyright 2106-2018 D. Mitch Bailey  cvc at shuharisystem dot com
 
 #   This program is free software: you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -36,13 +36,14 @@ if [[ ! -f $RULEFILE ]]; then
 	exit 1
 fi
 
+while [[ -L $DATA ]]; do
+	DATA=`readlink $DATA`
+done
+
 additionalRules="cvc.include"
 #   Additional rules include the following statements
-#   CASE (except LVS CASE[included later])
-#   VIRTUAL CONNECT COLON YES (if used)
-#   LVS (except LVS SOFTCHK[ignored], LVS REPORT/WRITE[fixed], LVS INJECT LOGIC[always NO], and
-#     LVS CULL PRIMITIVE CELLS[should be no for box instances])
-#   TRACE
+#   Switches for CVC
+#   Device filters for CVC
 
 cellOverrides="override.list"
 #   Cell overrides are
@@ -63,6 +64,27 @@ fi
 
 log="cdl.log"
 echo "log file: $log"
+
+if [[ ( $DATA -nt expand.list ) \
+		|| ( $cellOverrides -nt expand.list ) \
+		|| ( ! -s expand.list ) ]]; then
+	echo "Finding cells to expand using $cellOverrides ..."
+	if [[ -f $cellOverrides ]]; then
+		expand_cells.py $cellOverrides $PRIMARY $DATA > expand.list
+		expand_status=$?
+	else
+		echo "Warning: missing $cellOverrides"
+		expand_cells.py /dev/null $PRIMARY $DATA > expand.list
+		expand_status=$?
+	fi
+	if [[ $expand_status -ne 0 ]]; then
+		echo "ERROR: could not create expand.list"
+		rm -f expand.list
+		exit 1
+	fi
+else
+	echo "Reusing expand.list"
+fi
 
 cat > $rulefile <<-svs_rule
 	LAYOUT PRIMARY $PRIMARY
@@ -104,18 +126,6 @@ sed -e 's/[   ][      ]*/ /g' \
 	-e 's/^ *LVS EXECUTE ERC/\/\/&/I' \
 	-e 's/^ *MASK SVDB DIRECTORY/\/\/&/I' $RULEFILE >> $rulefile
 
-
-if [[ ( $DATA -nt expand.list ) || ( $cellOverrides -nt expand.list ) ]]; then
-	echo "Finding cells to expand using $cellOverrides ..."
-	if [[ -f $cellOverrides ]]; then
-		expand_cells.py $cellOverrides $PRIMARY $DATA > expand.list
-	else
-		echo "Warning: missing $cellOverrides"
-		expand_cells.py /dev/null $PRIMARY $DATA > expand.list
-	fi
-else
-	echo "Reusing expand.list"
-fi
 cat expand.list >> $rulefile
 
 if [[ -f $OUTPUT.0 ]]; then
@@ -133,15 +143,15 @@ echo "Removing leading double characters and changing commented parameters ..."
 # == -> --
 # $a -> a
 # $SUB= -> SUB= -> $SUB=  (no change)
-sed -e 's/^¥(.¥)¥1/¥1/' ¥
-    -e 's/¥$SUB=/^SUB=/' ¥
-    -e 's/¥$LDD//' ¥
-    -e 's/¥$//g' ¥
-    -e 's/^¥([^ ]*¥)==[0-9]*/¥1/' ¥
-    -e 's/^¥([^ ]*¥)==[0-9]*/¥1/' ¥
-    -e 's/==/--/g' ¥
-    -e 's/¥$//g' ¥
-    -e 's/¥^SUB=/$SUB=/' $OUTPUT.0 | ¥
+sed -e 's/^\(.\)\1/\1/' \
+    -e 's/\$SUB=/^SUB=/' \
+    -e 's/\$LDD//' \
+    -e 's/\$//g' \
+    -e 's/^\([^ ]*\)==[0-9]*/\1/' \
+    -e 's/^\([^ ]*\)==[0-9]*/\1/' \
+    -e 's/==/--/g' \
+    -e 's/\$//g' \
+    -e 's/\^SUB=/$SUB=/' $OUTPUT.0 | \
 $BOX_FILTER > $OUTPUT
 
 if [[ ! -z "${compress+x}" ]]; then
